#!/usr/bin/env python

"""
Tool file: cif2pdb

Codebase: /mcce4/pdb_conversions.py
"""
import sys

from mcce4.pdb_conversions import to_cif_cli


if __name__ == "__main__":
    sys.exit(to_cif_cli())
