#!/usr/bin/env python

"""
Tool file: clear_mcce_folder

Codebase: /mcce4/clear_mcce_outputs.py
"""
import sys

from mcce4.clear_mcce_outputs import cli

if __name__ == "__main__":
    sys.exit(cli())
