#!/usr/bin/env python3

"""
Tool file: cif2pdb

Codebase: /mcce4/cif_conversions.py
"""
import sys

from mcce4.cif_conversions import to_cif_cli


if __name__ == "__main__":
    sys.exit(to_cif_cli())
