#!/usr/bin/env python3

"""
Tool file: filesdiff

Diffing applicable to these files:
    "entropy.out",
    "fort.38",
    "head3.lst",
    "pK.out",
    "sum_crg.out",
    "vdw0.lst"
"""

import sys
from mcce4.diffing import diff_cli


if __name__ == "__main__":
    sys.exit(diff_cli())
