#!/usr/bin/env python3

"""
Tool file: get_aver_pqr

Codebase: /mcce4/average_pqr.py
"""
import sys

from mcce4.average_pqr import get_aver_pqr_cli


if __name__ == "__main__":
    sys.exit(get_aver_pqr_cli())
