#!/usr/bin/env python3

"""
Tool file:  md_fix_psf_mdanalysis

Codebase: mcce4/md_fix_psf_mdanalysis.py
"""
import sys

from mcce4.md_fix_psf_mdanalysis import cli


if __name__ == "__main__":
    sys.exit(cli())
