#!/usr/bin/env python3

"""
Tool file: ms_hbond_percentages

Codebase: /mcce4/ms_hbond_percentages.py
"""
import sys

from mcce4.ms_hbond_percentages import cli


if __name__ == "__main__":
    sys.exit(cli())
