#!/usr/bin/env python3

"""
Tool file:  ms_hbnets4_stats

Codebase: mcce4/stats_hbond_networks.py
"""
import sys

from mcce4.stats_hbond_networks import cli


if __name__ == "__main__":
    sys.exit(cli())
