#!/usr/bin/env python3

"""
Tool file:  ms_hbnets2_hah

Codebase: /mcce4/collect_ms_pdbs_hbonds.py
"""
import sys

from mcce4.collect_ms_pdbs_hbonds import cli


if __name__ == "__main__":
    sys.exit(cli())
