#!/usr/bin/env python

"""
Tool file: ms_protonation

Codebase: /mcce4/cms_analysis_wc/
"""
import sys

from mcce4.cms_analysis_wc.cli import crgmswc_cli

if __name__ == "__main__":
    sys.exit(crgmswc_cli())
