#!/usr/bin/env python3

"""
Tool: pI

Obtain the pI theoretical pI of the input protein pdb file (standard or mcce).
If 'sum_crg.out' exists in the pdb parent folder, then the protein pI is also
calculated, along with the delta (protein pI - theoretical pI).

Note: There must be at least 10 titration points in sum_crg.out.
"""
import sys

from mcce4.pi import cli


if __name__ == "__main__":
    sys.exit(cli())
